CREATE TABLE "daily-summaries-2000" (
    "STATION" VARCHAR,
    "LATITUDE" VARCHAR,
	"LONGITUDE" VARCHAR,
	"ELEVATION" VARCHAR,
	"DATE" date,
	"TMAX" VARCHAR,
	"TMIN" VARCHAR,
	"TOBS" VARCHAR   
);
CREATE TABLE "daily-summaries-2003" (
    "STATION" VARCHAR,
    "LATITUDE" VARCHAR,
	"LONGITUDE" VARCHAR,
	"ELEVATION" VARCHAR,
	"DATE" date,
	"TMAX" VARCHAR,
	"TMIN" VARCHAR,
	"TOBS" VARCHAR   
);
CREATE TABLE "daily-summaries-2006" (
    "STATION" VARCHAR,
    "LATITUDE" VARCHAR,
	"LONGITUDE" VARCHAR,
	"ELEVATION" VARCHAR,
	"DATE" date,
	"TMAX" VARCHAR,
	"TMIN" VARCHAR,
	"TOBS" VARCHAR   
);
CREATE TABLE "daily-summaries-2009" (
    "STATION" VARCHAR,
    "LATITUDE" VARCHAR,
	"LONGITUDE" VARCHAR,
	"ELEVATION" VARCHAR,
	"DATE" date,
	"TMAX" VARCHAR,
	"TMIN" VARCHAR,
	"TOBS" VARCHAR   
);
CREATE TABLE "daily-summaries-2012" (
    "STATION" VARCHAR,
    "LATITUDE" VARCHAR,
	"LONGITUDE" VARCHAR,
	"ELEVATION" VARCHAR,
	"DATE" date,
	"TMAX" VARCHAR,
	"TMIN" VARCHAR,
	"TOBS" VARCHAR   
);
CREATE TABLE "daily-summaries-2015" (
    "STATION" VARCHAR,
    "LATITUDE" VARCHAR,
	"LONGITUDE" VARCHAR,
	"ELEVATION" VARCHAR,
	"DATE" date,
	"TMAX" VARCHAR,
	"TMIN" VARCHAR,
	"TOBS" VARCHAR   
);
CREATE TABLE "daily-summaries-2018" (
    "STATION" VARCHAR,
    "LATITUDE" VARCHAR,
	"LONGITUDE" VARCHAR,
	"ELEVATION" VARCHAR,
	"DATE" date,
	"TMAX" VARCHAR,
	"TMIN" VARCHAR,
	"TOBS" VARCHAR   
);
CREATE TABLE "emission_data" (
    "State" VARCHAR,
    "1990" VARCHAR,
	"1991" VARCHAR,
	"1992" VARCHAR,
	"1993" VARCHAR,
	"1994" VARCHAR,
	"1995" VARCHAR,
	"1996" VARCHAR,
	"1997" VARCHAR,
	"1998" VARCHAR,
	"1999" VARCHAR,
	"2000" VARCHAR,
	"2001" VARCHAR,
	"2002" VARCHAR,
	"2003" VARCHAR,
	"2004" VARCHAR,
	"2005" VARCHAR,
	"2006" VARCHAR,
	"2007" VARCHAR,
	"2008" VARCHAR,
	"2009" VARCHAR,
	"2010" VARCHAR,
	"2011" VARCHAR,
	"2012" VARCHAR,
	"2013" VARCHAR,
	"2014" VARCHAR,
	"2015" VARCHAR,
	"2016" VARCHAR,
	"2017" VARCHAR,
	"2018" VARCHAR	
);